version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PARTNER_INTEGRATION
